version: "3.9"

services:
  db:
    container_name: tac_db_1
    image: postgres:15.1
    restart: always
    build:
      context: ./docker/postgres/
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - data:/var/lib/postgresql/data
  
volumes:
  data:
    driver: "local"
